theme: minima
title: MeRIT
description: Method Reporting with Initials for Transparency
header_pages:
  - Community_Examples.md 
  - Benefits.md
  - FAQ.md
  - MeRITPeople.md
  - Contribute.md
  - Cite.md
